name: pull_to_reach
description: Pull to reach implemention for TiO
version: 0.0.1
author: Julian Bissekkou
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: